/**
 * Entity types constants
 */
export const EntityTypes = {
  LEADS: 'leads',
  LEAD: 'lead',
  LEADS_PIPELINES: 'pipelines',
  LEADS_LOSS_REASONS: 'loss_reasons',
  LEADS_STATUSES: 'statuses',
  SOURCES: 'sources',
  CONTACTS: 'contacts',
  CONTACT: 'contact',
  CATALOGS: 'catalogs',
  FILES: 'files',
  COMPANIES: 'companies',
  CONTACTS_AND_COMPANIES: 'contacts_and_companies',
  COMPANY: 'company',
  CUSTOMERS: 'customers',
  CUSTOMERS_TRANSACTIONS: 'transactions',
  EVENTS: 'events',
  EVENTS_TYPES: 'events_types',
  NOTES: 'notes',
  TAGS: 'tags',
  TASKS: 'tasks',
  WEBHOOKS: 'webhooks',
  UNSORTED: 'unsorted',
  CATALOG_ELEMENTS: 'elements',
  CATALOG_ELEMENTS_FULL: 'catalog_elements',
  USER_ROLES: 'roles',
  USERS: 'users',
  CUSTOMERS_SEGMENTS: 'segments',
  CUSTOMERS_STATUSES: 'statuses',
  WIDGETS: 'widgets',
  STATUS_RIGHTS: 'status_rights',
  CATALOG_RIGHTS: 'catalog_rights',
  CALLS: 'calls',
  PRODUCTS: 'products',
  SETTINGS: 'settings',
  SHORT_LINKS: 'short_links',
  LINKS: 'links',
  TALKS: 'talks',
  SUBSCRIPTIONS: 'subscriptions',
  CURRENCIES: 'currencies',
  CUSTOM_FIELDS: 'custom_fields',
  CUSTOM_FIELD_GROUPS: 'custom_field_groups',
  DEFAULT_CATALOG_TYPE_STRING: 'regular',
  INVOICES_CATALOG_TYPE_STRING: 'invoices',
  PRODUCTS_CATALOG_TYPE_STRING: 'products',
  SUPPLIERS_CATALOG_TYPE_STRING: 'suppliers',
  CHAT_TEMPLATES: 'chat_templates',
  WEBSITE_BUTTONS: 'website_buttons',
  MIN_CATALOG_ID: 1000,
} as const;

export type EntityType = (typeof EntityTypes)[keyof typeof EntityTypes];
